# Using Panel Data Viz

In [22]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')

import hvplot.pandas

In [23]:
# df = pd.read_csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")

In [24]:
# cache data to improve dashboard performance
if 'data' not in pn.state.cache.keys():

    df = pd.read_csv('https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv')

    pn.state.cache['data'] = df.copy()

else: 

    df = pn.state.cache['data']

In [25]:
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_oil_co2,share_global_other_co2,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1949,AFG,7624058.0,NaN,NaN,NaN,0.015,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1950,AFG,7752117.0,9.421400e+09,NaN,NaN,0.084,0.070,475.0,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1951,AFG,7840151.0,9.692280e+09,NaN,NaN,0.092,0.007,8.7,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1952,AFG,7935996.0,1.001733e+10,NaN,NaN,0.092,0.000,0.0,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1953,AFG,8039684.0,1.063052e+10,NaN,NaN,0.106,0.015,16.0,...,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [26]:
df[df['country'] == 'North America']

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_oil_co2,share_global_other_co2,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
16783,North America,1785,NaN,NaN,NaN,NaN,NaN,0.004,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16784,North America,1786,NaN,NaN,NaN,NaN,NaN,0.004,0.000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16785,North America,1787,NaN,NaN,NaN,NaN,NaN,0.004,0.000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16786,North America,1788,NaN,NaN,NaN,NaN,NaN,0.004,0.000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16787,North America,1789,NaN,NaN,NaN,NaN,NaN,0.004,0.000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17014,North America,2016,NaN,573814471.0,NaN,70.858,0.124,6471.359,-141.345,-2.14,...,33.15,16.69,20.85,27.28,24.07,10.10,7461.92,7611.92,309.904,4.79
17015,North America,2017,NaN,578582939.0,NaN,72.914,0.127,6412.982,-58.378,-0.90,...,32.94,16.44,17.93,26.34,23.85,9.76,7418.35,7566.23,335.009,5.22
17016,North America,2018,NaN,582921778.0,NaN,74.787,0.129,6588.630,175.648,2.74,...,32.76,16.18,21.02,27.59,24.16,8.71,7630.50,7777.59,345.915,5.25
17017,North America,2019,NaN,587512602.0,NaN,76.925,0.132,6460.726,-127.904,-1.94,...,32.57,15.92,23.12,28.02,23.94,8.37,7515.65,7663.03,354.353,5.48
17018,North America,2020,NaN,592062325.0,NaN,76.870,0.131,5775.159,-685.568,-10.61,...,32.39,15.68,23.09,27.81,23.02,8.53,NaN,NaN,NaN,NaN

In [27]:
df[df['country'] == 'World']

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_oil_co2,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_oil_co2,share_global_other_co2,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
25477,World,1750,NaN,7.456645e+08,NaN,NaN,NaN,9.351,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25478,World,1751,NaN,NaN,NaN,NaN,NaN,9.351,0.000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25479,World,1752,NaN,NaN,NaN,NaN,NaN,9.354,0.004,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25480,World,1753,NaN,NaN,NaN,NaN,NaN,9.354,0.000,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25481,World,1754,NaN,NaN,NaN,NaN,NaN,9.358,0.004,0.04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25743,World,2016,NaN,7.464335e+09,1.071343e+14,1478.758,0.198,35452.461,-43.947,-0.12,...,100.0,80.03,100.0,100.0,100.0,100.0,47531.680,46264.070,-0.0,-0.0
25744,World,2017,NaN,7.548173e+09,1.104307e+14,1500.493,0.199,35925.738,473.278,1.33,...,100.0,80.75,100.0,100.0,100.0,100.0,48251.879,47031.820,0.0,0.0
25745,World,2018,NaN,7.631081e+09,1.136302e+14,1566.740,0.205,36646.141,720.402,2.01,...,100.0,81.41,100.0,100.0,100.0,100.0,49368.039,47980.469,-0.0,-0.0
25746,World,2019,NaN,7.713458e+09,NaN,1608.472,0.208,36702.504,56.363,0.15,...,100.0,82.03,100.0,100.0,100.0,100.0,49758.230,48116.559,0.0,0.0
25747,World,2020,NaN,7.794789e+09,NaN,1626.371,0.209,34807.258,-1895.244,-5.16,...,100.0,82.60,100.0,100.0,100.0,100.0,NaN,NaN,0.0,0.0

(0) Some minor data preprocessing

In [28]:
# Fill NAs with 0s and create GDP per capita column
df = df.fillna(0)
df['gdp_per_capita'] = np.where(df['population']!= 0, df['gdp']/ df['population'], 0)

In [29]:
# Make DataFrame Pipeline Interactive
idf = df.interactive()

(1) CO2 emission over time by continent

In [30]:
# Define Panel widgets
year_slider = pn.widgets.IntSlider(name='Year slider', start=1750, end=2020, step=5, value=1850)
year_slider

TypeError: _repr_mimebundle_() takes 1 positional argument but 3 were given

IntSlider(end=2020, name='Year slider', start=1750, step=5, value=1850)

In [ ]:
# Radio buttons for CO2 measures
yaxis_co2 = pn.widgets.RadioButtonGroup(
    name='Y axis', 
    options=['co2', 'co2_per_capita',],
    button_type='success'
)

In [ ]:
continents = ['World', 'Asia', 'Oceania', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

co2_pipeline = (
    idf[
        (idf.year <= year_slider) &
        (idf.country.isin(continents))
    ]
    .groupby(['country', 'year'])[yaxis_co2].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [ ]:
co2_pipeline

TypeError: _repr_mimebundle_() takes 1 positional argument but 3 were given

In [ ]:
co2_plot = co2_pipeline.hvplot(x = 'year', by='country', y=yaxis_co2,line_width=2, title="CO2 emission by continent")
co2_plot

c:\Users\Utente77\repos\insiders_clustering_ecommerce\dataviz\lib\site-packages\holoviews\core\data\pandas.py:221: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  data = [(k, group_type(v, **group_kwargs)) for k, v in
c:\Users\Utente77\repos\insiders_clustering_ecommerce\dataviz\lib\site-packages\holoviews\core\data\pandas.py:221: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  data = [(k, group_type(v, **group_kwargs)) for k, v in

TypeError: _repr_mimebundle_() takes 1 positional argument but 3 were given

(2) Table - CO2 emission over time by continent

In [ ]:
co2_table = co2_pipeline.pipe(pn.widgets.Tabulator, pagination='remote', page_size = 10, sizing_mode='stretch_width') 
co2_table

(3) CO2 vs GDP scatterplot

In [ ]:
co2_vs_gdp_scatterplot_pipeline = (
    idf[
        (idf.year == year_slider) &
        (~ (idf.country.isin(continents)))
    ]
    .groupby(['country', 'year', 'gdp_per_capita'])['co2'].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [ ]:
co2_vs_gdp_scatterplot_pipeline

NameError: name 'co2_vs_gdp_scatterplot_pipeline' is not defined

In [ ]:
co2_vs_gdp_scatterplot = co2_vs_gdp_scatterplot_pipeline.hvplot(x='gdp_per_capita', 
                                                                y='co2', 
                                                                by='country', 
                                                                size=80, kind="scatter", 
                                                                alpha=0.7,
                                                                legend=False, 
                                                                height=500, 
                                                                width=500)
co2_vs_gdp_scatterplot

(4) Bar chart with CO2 sources by continent

In [ ]:
yaxis_co2_source = pn.widgets.RadioButtonGroup(
    name='Y axis', 
    options=['coal_co2', 'oil_co2', 'gas_co2'], 
    button_type='success'
)

continents_excl_world = ['Asia', 'Oceania', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

co2_source_bar_pipeline = (
    idf[
        (idf.year == year_slider) &
        (idf.country.isin(continents_excl_world))
    ]
    .groupby(['year', 'country'])[yaxis_co2_source].sum()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [ ]:
co2_source_bar_plot = co2_source_bar_pipeline.hvplot(kind='bar', 
                                                     x='country', 
                                                     y=yaxis_co2_source, 
                                                     title='CO2 source by continent')
co2_source_bar_plot

Creating Dashboard

In [ ]:
#Layout using Template
template = pn.template.FastListTemplate(
    title='World CO2 emission dashboard', 
    sidebar=[pn.pane.Markdown("# CO2 Emissions and Climate Change"), 
             pn.pane.Markdown("#### Carbon dioxide emissions are the primary driver of global climate change. Itâ€™s widely recognised that to avoid the worst impacts of climate change, the world needs to urgently reduce emissions. But, how this responsibility is shared between regions, countries, and individuals has been an endless point of contention in international discussions."), 
             pn.pane.PNG('climate_day.png', sizing_mode='scale_both'),
             pn.pane.Markdown("## Settings"),   
             year_slider],
    main=[pn.Row(pn.Column(yaxis_co2, 
                           co2_plot.panel(width=700), margin=(0,25)), 
                 co2_table.panel(width=500)), 
          pn.Row(pn.Column(co2_vs_gdp_scatterplot.panel(width=600), margin=(0,25)), 
                 pn.Column(yaxis_co2_source, co2_source_bar_plot.panel(width=600)))],
    accent_base_color="#88d8b0",
    header_background="#88d8b0",
)
# template.show()
template.servable();